before_script:
  - echo "Starting CI - Vegas Ingest"

stages:
  - build

# Build do Pacote pelo Maven para geração do JAR
build_package:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
    - mvn clean package

after_script:
  - echo "End CI - Vegas Ingest"
