spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: vegas-ingest
        url: jdbc:mysql://xxxxxxxxxx:3309/vegas
        username: vegas-ingest
    jpa:
        hibernate:
            ddl-auto: create    
