spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: xxxxxxxxxxx
        url: jdbc:mysql://xxxxxxxxxx:3309/vegas
        username: xxxxxxxxxxx
    jpa:
        hibernate:
            ddl-auto: create    
